name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to DigitalOcean VPS
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@1.0.3
        with:
          host: 161.35.188.47
          port: 22
          username: laracasts
          key: ${{secrets.PRIVATE_KEY}}
          script: "cd www; git pull"

